### ISSUE TITLE
get_sent_list issue

### ISSUE THREAD

**Issue by lijunforNLPtraining** [iwkiwk/nlp-course#2]
def get_sent_list(self, word_list, start, periods):
        ret = []
        if len(periods) == 0:
            ret.append(list(word_list[start + 1:]))
        for i, p in enumerate(periods):
            if i == 0:
                ret.append(list(word_list[start + 1:p + 1]))
            else:
                ret.append(list(word_list[periods[i - 1] + 1:p + 1]))
        return ret
if if len(periods) == 0 ， ret should append list(word_list[root_index+1:])???????,not list(word_list[start + 1:])?

**Comment by iwkiwk** [comment]
差不太多，有时候会有少包含一个左引号的情况。我针对的是“新华日报称，”，“小明说：”这种，如果是“小明说”直接跟引号会少包含一个左引号，没做那么细

**Comment by lijunforNLPtraining** [comment]
学习了
